name: Deploy Flask App

on:
  push:
    branches:
      - master


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |

        pip install -r requirements.txt

    - name: Build and Run Flask App
      run: |

        export FLASK_APP=app.py
        export FLASK_ENV=development # Set this to "development" if you want to run in development mode
        flask run --host=0.0.0.0 --port=443

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.github_token }}
        publish_branch: master
        publish_dir: ./static # Replace with the directory where your app's static files are stored
